# Generated by Django 4.2.2 on 2023-10-20 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_advertisement_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='favorite',
        ),
    ]
